channels:
  - conda-forge
dependencies:
  - python=3.11.13
  - numpy=2.3.*
  - pandas=2.3.*
  - scikit-learn=1.7.*
  - matplotlib=3.10.*
  - seaborn=0.13.*
  - jupyterlab=4.4.*
  - ipywidgets=8.1.*
  - ipykernel=6.30.*
