[project]
name = "config-recommendation-ml"
author = "Maciej Czechowski <maciej.czechowski090@gmail.com>"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"

[tool.ruff]
line-length = 88
target-version = "py311"
extend-select = ["I"] 
show-fixes = true

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = []
# E - PEP8 błędy formatowania
# F - flake8 (błędy Python)
# B - bugbear (dodatkowe potencjalne błędy)
# I - importy (isort)

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.isort]
known-first-party = ["config-recommendation-ml"]
combine-as-imports = true
force-single-line = false

